[distracting]
meme = 30
youtube = 50
"official video" = 47
visualizer = 47
linkedin = 42
dating = 30
"youtube music" = 50
song = 50
artist = 50
abt = 50
"love stories" = 40
gossip = 50
celebrity = 50
music = 45
prison = 50
memes = 30
advice = 93
instagram = 30
stories = 40
tiktok = 30
love = 45
funny = 30
pov = 47
youtube_shorts = 40
lyrics = 50
songs = 50
facebook = 30
astrology = 45
audio = 47

[productive]
"western governors university" = -42
certifications = -45
mindfulness = -40
comptia = -45
study = -45
learning = -30
calculus = -42
cisco = -45
wgu = -30
"realitty transurfing" = -45
math = -50
pcb = -30
labs = -15
github = -20
python = -20
terminal = -30
data = -45
troubleshoot = -40
wikipedia = -45
electronics = -30
communication = -45
coding = -20
algebra = -33
networks = -45
workout = -40
chatgpt = -45
projects = -45
rust = -20
communicate = -45
geeksquad = -25
kitty = -30
learn = -30
mathematics = -50
books = -45
ccna = -50
mindful = -40
network = -45
dynjee = -25
"google docs" = -45
networking = -45
gym = -40
linux = -15
